### ISSUE TITLE
vagrant test env needs db w/ data and with "fake" admin users for testing

### ISSUE THREAD

**Issue by jessemtso** [yedi/garpr#17]
vagrant test env needs db w/ data and with "fake" admin users for testing

should be a DB dump that has actual tournaments (for testing autosuggest, merges, and other admin functionality.

also will need to have "fake" admin accounts (un: test, passwd: test) because this is going in source control, so we dont wanna leak our (hashed) creds

**Comment by jessemtso** [comment]
yedi gave me a DB dump, @acoulon99 integrate it into the vagrant env so its loaded by default. 

creds are admin/admin

[garpr-db.zip](https://github.com/yedi/garpr/files/299034/garpr-db.zip)

**Comment by jschnei** [comment]
I think this PR should fix this; test it out.

**Comment by jessemtso** [comment]
why was this reopened? does https://github.com/yedi/garpr/pull/25 fix this?

**Comment by jschnei** [comment]
I think I accidentally closed this when I posted my comment. Probably can be closed when #25 is accepted.

**Comment by jessemtso** [comment]
we're close... we have a real db being imported. does it have a garpr admin user in its db yet?

**Comment by Jdtanacredi** [comment]
The db that was in the codebase last night had an admin user, but the hashed password wasn't admin.

**Comment by jessemtso** [comment]
one issue might be that the password was generated with an earlier version of garPR (and so was encoded differently). try running change_password to change the user’s password to admin.

**Comment by jschnei** [comment]
#29 should change admin's password back to admin.

**Comment by jessemtso** [comment]
https://github.com/yedi/garpr/pull/29
