### ISSUE TITLE
Admin feature request: ability to delete tournaments

### ISSUE THREAD

**Issue by VestboyMyst** [yedi/garpr#3]
title says it all. currently only yedi can delete brackets once they are submitted.

damien said he worked on a way to delete brackets in 'pending' queue but that doesn't seem to work either

**Comment by jiangtyd** [comment]
well, the `DELETE /tournament/{id}/` route definitely exists

**Comment by jessemtso** [comment]
no, thats just to delete a pending tournament. will need to add in a thing to let admins delete regular (non-pending) tournaments

**Comment by jessemtso** [comment]
assigning this to me

**Comment by jessemtso** [comment]
the route now properly handles both pending and finalized tournaments. there's code testing the auth as well.

just need front-end for it now

**Comment by jessemtso** [comment]
closed by https://github.com/yedi/garpr/pull/31
