### ISSUE TITLE
Not auto filling the players in any nebs primes even though all tags are common

### ISSUE THREAD

**Issue by hbacker94** [yedi/garpr#6]
the auto fill function is not working for tags that are very slightly different from the actual tags. for exampl "1  1  Slox" should become "Slox." some of the names will autofill for example- http://njssbm.com/#/nyc/tournaments/574c5d9ce5925732410756df

in this link you can see that NY Joey was auto filled correctly, while every other name has no suggestion come up. these are all common tags, Capt Smuckers, Slox, G$. 

tldr - 1 1 Slox = Slox

**Comment by jiangtyd** [comment]
I wrote it as an "experimental" feature (basically we look at stuff after `|`), but we can probably handle the pools thing in a sort-of-hardcoded way, I think.

**Comment by jiangtyd** [comment]
@hbacker94 in the meantime, TOs can work around this by denoting pools by something like 
```1 1 - Slox```

**Comment by jhertz** [comment]
Ill fix this damien, wheres the source file
For autofilling?

**Comment by jiangtyd** [comment]
@jhertz https://github.com/yedi/garpr/blob/master/dao.py#L266 is the relevant part (it's called by https://github.com/yedi/garpr/blob/master/alias_service.py, but you shouldn't need to change stuff there I think)

**Comment by jhertz** [comment]
Well, were trying to import existing tournaments, so we should try and make some changes that help the importers

**Comment by jessemtso** [comment]
this is done, just need Yedi to push to prod
