### ISSUE TITLE
nosetests not installed, and fails within vagrant env

### ISSUE THREAD

**Issue by jessemtso** [yedi/garpr#8]
boot VM
`nosetests` -- not found
run `sudo apt-get install python-nose`
run `nosetests` will fail with a bunch of import errors
something is not working correctly with python environment (nose *is* included in requirements.txt)

**Comment by acoulon99** [comment]
on it!

**Comment by jessemtso** [comment]
nosetests runs now!

we are failing some tests, looking into it

**Comment by jessemtso** [comment]
looks like a big issue is that we're not importing something from hashlib correctly, a lot of tests fail with something like this:

======================================================================
ERROR: test_delete_player_region (test.test_server.TestServer)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/vagrant/test/test_server.py", line 45, in setUp
    self._create_users(self.mongo_client)
  File "/home/vagrant/test/test_server.py", line 89, in _create_users
    hashed_password = hashlib.pbkdf2_hmac('sha256', 'rip', salt, ITERATION_COUNT)
AttributeError: 'module' object has no attribute 'pbkdf2_hmac'

**Comment by acoulon99** [comment]
I'll take a look tonight

**Comment by jessemtso** [comment]
closed by PR https://github.com/yedi/garpr/pull/14
